services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  redis-insight:
    container_name: "redis-insight"
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
